### ISSUE TITLE
[Bug] FW_ArrayContains missing

### ISSUE THREAD

**Issue by siekermantechnology** [rokudev/unit-testing-framework#7] opened 2016-11-17 14:38 UTC
Several functions in fw_baseTestSuite.brs make use of the function FW_ArrayContains, but that appears to be missing. I assume there is another support file similar to fw_types.brs and fw_strings.brs which contains that function. If so, please add that.

**Comment by EnTerr** [comment] 2016-12-31 16:03
<rolls eyes>

**Comment by samdozor** [comment] 2017-01-05 15:20
This is a duplicate of https://github.com/rokudev/unit-testing-framework/issues/2, addressed by https://github.com/rokudev/unit-testing-framework/pull/12

**Comment by RokuRnD** [comment] 2017-01-25 16:56
Thank you for filing the issue. New 1.1.0 version contains all the fixes.

**Closed by RokuRnD** 2017-01-25 16:56 UTC
